spring.application.name=coursespringboot

# App config

app.jwt.secret=yhuZs0OfR6mzK9Zu7Y6mDHueqYFrLN45

# Database config

spring.datasource.url=jdbc:sqlite:C:/Users/syntax/Desktop/db_test/course_spring_boot.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


# Cache config

spring.cache.type=redis
spring.data.redis.database=0
spring.data.redis.host=192.168.156.103
spring.data.redis.port=6379



# FOR DEBUG SQL

#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type=TRACE
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.hibernate.orm.jdbc.bind=TRACE

# FOR DEV
spring.jpa.hibernate.ddl-auto=update
spring.datasource.initialization-mode=always